name: multi_map_atlas
description: A Flutter multi map provider using Atlas

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_phoenix: ^0.1.0
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  atlas: 0.12.2
  here_maps_atlas:
    git:
      url: https://github.com/edsondiasalves/here_maps_atlas.git
      ref: v1.3.1
  google_maps_atlas:
    git:
      url: https://github.com/edsondiasalves/google_maps_atlas.git
      ref: v1.3.1
  mapbox_atlas:
    git:
      url: https://github.com/edsondiasalves/mapbox_atlas.git
      ref: v1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

